# Basic Info:
url: "http://www.ar-lab.cn"
baseurl: ""
title: AR Lab

# Original Theme:
theme: jekyll-theme-minimal

# Short description of your site
description: "This is a website for AR Lab."


# # --- Navigation bar options --- #
# navbar-font: 120px
# # List of links in the navigation bar
# navbar-links:
#   About: ""
#   News: "news"
#   People: 
#     - Current Members: "current"
#     - Lab Alumni: "alumni"
#     - Lab Visitors: "Visitors"
#   # Publication: "shanghaitecharlab.github.io/publication/"
#   Research: "research"
#   Join Us: "join"

# avatar: "/img/avatar-icon.jpg"

# # Personalize the colors in your website. Colour values can be any valid CSS colour
# navbar-col: "#F5F5F5"
# navbar-text-col: "#404040"
# navbar-children-col: "#F5F5F5"
# page-col: "#FFFFFF"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# footer-col: "#F5F5F5"
# footer-text-col: "#777777"
# footer-link-col: "#404040"


# # --- Footer options --- #
# author:
#   name: <a href="www.ar-lab.cn">Attitude Research Laboratory</a> @ <a href="http://www.shanghaitech.edu.cn">ShanghaiTech University</a>
#   